/**
 * EVOLVE System Prompt Injection
 *
 * This module provides the hook that injects Evolve's learned context
 * into Voracode's system prompt at session start.
 *
 * Integration point: This should be called from prompt.ts where the
 * system prompt array is assembled.
 *
 * Current Voracode flow (prompt.ts ~line 1264):
 *   const system = [
 *     ...env,           // Environment info
 *     ...instructions,  // AGENTS.md, CLAUDE.md, etc.
 *     ...mcpInstructions,
 *     ...skills,
 *   ]
 *
 * With Evolve:
 *   const system = [
 *     ...env,
 *     ...instructions,
 *     ...mcpInstructions,
 *     ...skills,
 *     ...evolveContext,  // ← NEW: Evolve's learned context
 *   ]
 */

import { EvolveEngine } from "./engine"
import { Memory } from "./memory"
import { Conventions } from "./conventions"
import { SkillLibrary } from "./skills"
import { Reflection } from "./reflection"
import { AdaptiveContext } from "./adaptive-context"

// ─── Main Injection Function ─────────────────────────────────────────────────

/**
 * Generate Evolve context strings to inject into the system prompt.
 *
 * @param projectPath - The project directory path
 * @param query - The current user query (for adaptive context)
 * @returns Array of strings to append to the system prompt
 */
export async function generateEvolveContext(
  projectPath: string,
  query?: string,
): Promise<string[]> {
  try {
    // Initialize components
    const memory = new Memory(projectPath)
    await memory.init()

    const skills = new SkillLibrary(projectPath)
    await skills.init()

    const conventions = new Conventions(projectPath)

    // Check if we have any learned context
    const memoryEntries = memory.getAllEntries()
    const allSkills = skills.getAll()

    if (memoryEntries.length === 0 && allSkills.length === 0) {
      // No learned context yet — skip injection
      return []
    }

    // Build context using adaptive strategy
    const reflection = new Reflection(memory)
    const adaptiveContext = new AdaptiveContext(memory, conventions, skills, reflection)

    const strategy = adaptiveContext.selectStrategy(query ?? "")
    const bundle = await adaptiveContext.buildContext(query ?? "", strategy)

    if (!bundle.systemPrompt) return []

    // Wrap in a clear section header so the LLM knows this is learned context
    const wrapped = [
      "---",
      "# Learned Project Context (Auto-Generated by Voracode Evolve)",
      "",
      "The following context was automatically learned from previous sessions.",
      "Use it to provide more consistent and project-aware assistance.",
      "",
      bundle.systemPrompt,
      "---",
    ].join("\n")

    return [wrapped]
  } catch (error) {
    // Non-fatal: Evolve should never block session startup
    console.error("[Evolve] Context injection error:", error)
    return []
  }
}

/**
 * Lightweight version that only loads memory (no skills/conventions analysis).
 * Use this for quick context injection when full analysis isn't needed.
 */
export async function generateQuickEvolveContext(
  projectPath: string,
  maxEntries: number = 20,
): Promise<string[]> {
  try {
    const memory = new Memory(projectPath)
    await memory.init()

    const context = memory.toContext(maxEntries)
    if (!context) return []

    return [
      "---",
      "# Learned Project Context (Voracode Evolve)",
      "",
      context,
      "---",
    ]
  } catch {
    return []
  }
}

/**
 * Check if Evolve has any learned context for a project.
 * Use this to decide whether to run the full context generation.
 */
export async function hasEvolveContext(projectPath: string): Promise<boolean> {
  try {
    const memory = new Memory(projectPath)
    await memory.init()
    return memory.getAllEntries().length > 0
  } catch {
    return false
  }
}
